# Generated by Django 2.0 on 2018-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
